# -*- coding: utf-8 -*-
"""automobileparts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeEeSueKrM5EaUY2XnJbw_wZhQedPYhL
"""

class tire():
  def __init__(self):
    print("Tire created successfully!")

class steeringwheel():
  def __init__(self):
    print("Steering Wheel created successfully!")

class engine():
  def __init__(self):
    print("Engine created successfully!")

class door():
  def __init__(self):
    print("Door created successfully!")