# -*- coding: utf-8 -*-
"""campers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HgI48sj1YD5K-x4q5QzUn4O97ORI0EUx
"""

class Winnebago():
  def __init__(self):
    self._weight = 0
    print("Winnebago built")

  @property
  def weight(self):
    return self._weight

  @weight.setter
  def weight(self, w)
    self._weight = w

class Airstream():
  def __init__(self):
    self._weight = 0
    print("Airstream built")

  @property
  def weight(self):
    return self._weight

  @weight.setter
  def weight(self, w)
    self._weight = w