# -*- coding: utf-8 -*-
"""carfactory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeEeSueKrM5EaUY2XnJbw_wZhQedPYhL
"""

#carfactory.py
import cars

class CarFactory():

  numberOBuiltCars = 0

  def __init__(self):
    print("Car factory created successfully!")

  @classmethod
  def addAnotherCar(cls):
    cls.numberOBuiltCars += 1

  def buildCar(self, maker, model):
    CarFactory.addAnotherCar()
    return cars.Automobile(maker, model)