# -*- coding: utf-8 -*-
"""cars.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HeEeSueKrM5EaUY2XnJbw_wZhQedPYhL
"""

#cars.py
import automobileparts as ap

class Automobile():
  def __init__(self, maker, model):
    self._maker = maker
    self._model = model
    self._tires = {}
    for i in range(4):
      self._tires["tire" + (i+1)] = ap.tire()
    # I assume most cars have a trunk
    self._doors = {}
    for i in range(5):
      self._doors["door" + (i)] = ap.door()
    self._engine= ap.engine()
    self._steeringWheel = ap.steeringwheel()

    print("Automobile created successfully!")

  @property
  def maker(self):
    return self._maker
  @maker.setter
  def maker(self, maker):
    self._maker = maker
  @property
  def model(self):
    return self._maker
  @model.setter
  def model(self, model):
    self._model = model