# -*- coding: utf-8 -*-
"""Homework03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FBIKLnnmkSEkKR4_bHz4Nz-iRxqSNmst
"""

import sys
sys.path.append('content')
import Customer as c

"""
    Your program should open the input.txt file and read in each line of the file.
    As you read a line in you need to create a Customer object to store the account number and amount from the line.
    Each Customer object, after it is created and initialized with data, should be placed into a list.
    (Hint: Use the split function found in Appendix A to separate the account numbers from the
    amounts before you put them into the Customer object)
"""

#create list to store customer objects
cOBJ = []
#create try catch for file handling errors and debugging
try:
    #open file for reading (in correct directory)
    f = open ('input.txt', 'r')

    #for each line of the file split on the colon in order to
    #one get rid of the unessesary colon
    #two store account number and account amount
    for line in f:
        attributes = line.split(':')
        #type management
        if (attributes[1].isdigit()):
            attributes[1] = float(attributes[1])
        #create and store customer objects
        cOBJ.append(c.customer(attributes[0],attributes[1]))

    #close file
    f.close()
    print('File read correctly!')
#handle exception
except Exception as e:
    print("file failed to load!", e)
    pass

"""'''
    Your program should then go through the customer list and call the calculateInterestPayment method on each Customer object.
    This means each customer will get an interest payment added to their account.
'''
"""

#run interest payments only id customer objects were stored
if(cOBJ):
    for c in cOBJ:
        #don't calulate interest for header
        if (c._accountNumber == "Account#"):
            continue
        c.calculateInterestPayment()
    print("Interest applied to accounts...")

"""'''
    Your program will then need to create a file named output.csv that will contain all the
    customers with their new bank account amounts. Essentially the output.csv file will look like the
    input.txt file except that the colons will need to be replaced with commas.
    Here is what the output.xls file should resemble (Note the amounts listed are not the correct
    amounts because they are missing the interest payments):
    Account#,Amount
    42-8798,125988.87
    78-6746,43762.18
    34-1245,1243.21
    91-7483,13337.73
'''
"""

#create try catch for file handling errors and debugging
try:
    #open file for writing (in correct directory)(rewrite, don't append)
    k = open ('output.csv', 'w')

    #write to file only if customer objects were stored
    if(cOBJ):
        for c in cOBJ:
            #header must be written differently
            if (c._accountNumber == "Account#"):
                k.write("%s,%s" % (c._accountNumber,c._amount))
            #write all customers in comma seperated rows
            else:
                k.write("%s,%.2f\n" % (c._accountNumber, float(c._amount)))
    #close file
    k.close()
    print('Output file created!')
#handle exceptions
except Exception as e:
    print("file failed to write!", e)
    pass

"""'''
    Make sure to use try except on all reading and writing of files.
    This is necessary to capture errors such as file not found and/or data read/write errors.
    You will need to submit the input.txt, main.py, customer.py and output.xls file for grading.
'''
"""