# -*- coding: utf-8 -*-
"""W11A01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TEwOAf6WCKFcqTbyyGoqZd-yvnvro9sG

Week 11 assignment 1

simple notepad

date last modified: March 18, 2024

Make a program that will have user enter as many lines as they would like. The user will have to type finish for when you should stop recording data. Then you will save this to a text file, in which the user can choose the name of it. It will always be a .txt file.
"""

def takeSentence():
  x = input(">>> ")

  if('~Fin' in x):
    return False
  else:
    return x

import os

try:
  f = open("D:\College\SeniorYear\SpringSemester\IS-4485\WeeklyAssignments\file01.txt", 'w')

  unfinished = True
  print("Please enter the next line to add to file. \nEnter ~Fin to finish the file. \n")
  while(unfinished):
    next = takeSentence()

    if (next == False):
      unfinished = False
      print("Saving file...")
    else:
      f.write(next+'\n')

  name = input("please enter the file name: ")
  if name == '':
    pass
  else:
    os.rename("D:\College\SeniorYear\SpringSemester\IS-4485\WeeklyAssignments\file01.txt", "D:\College\SeniorYear\SpringSemester\IS-4485\WeeklyAssignments\\" + name + ".txt")
except Exception as e:
  print("File failed to write,", e, "\nPlease try again!")

print("File written successfully")
f.close()