# -*- coding: utf-8 -*-
"""W13A02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/166KK-3Yvu98AVzYWww3cmB7PYZX3znzb
"""

import automobileparts as ap
import carFactory

lefty = ap.tire()
righty = ap.steeringwheel()
upty = ap.engine()
rightDoor = ap.door()

why = carFactory.CarFactory()
did = why.buildCar("BMW", "M3")
timmy = why.buildCar("Toyota", "Forerunner")
print(why.numberOBuiltCars)

#cross the road?
#I thought I would need atleast three more variables