# -*- coding: utf-8 -*-
"""W13A01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TBTB1VLMtlXL-yATenR8q2wuV9668UWC
"""

class automobile():
  def __init__(self, price):
    self._price = price
    self._maker = "Ford"

  @classmethod
  def changeCarMaker(cls, name):
    cls.maker = name

  @property
  def price(self):
    return self._price

  @price.setter
  def price(self, nPrice):
    self._price = nPrice

  def __str__(self):
    return str(self._price)

mycar=automobile(600)
mycar.price = 5400
print(mycar.price)

car1 = automobile(600)
car2 = automobile(607)
car3 = automobile(35496)
automobile.changeCarMaker("Toyota")

print(car1.maker, car2.maker, car3.maker)

import campers as c
winnebago = c.Winnebago()
airstream = c.Airstream()
winnebago.weight = 7000
airstream.weight = 8000