# -*- coding: utf-8 -*-
"""W14A01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18sJ27haYbdiLX3Gm-BeXkezb3kPe73X9
"""

class Animal:
  def __init__(self,h,w,wid):

    self._weight=w
    self._height=h
    self._width=wid

  def eat(self):
    print("Animal eats.")

  @property
  def weight(self):
    return self._weight
  @property
  def height(self):
    return self._height
  @property
  def width(self):
    return self._width

  @weight.setter
  def weight(self, w):
    self._weight = w
  @height.setter
  def height(self, h):
    self._height = h
  @width.setter
  def width(self,w):
    self._width = w

class Dog(Animal):
  def __init__(self,h,w,wid):
    super().__init__(h,w,wid)
    self._legs = 4
    self._paws = 4
    self._isMammal=True
    self._eatsDogFood=True

  def eat(self):
    print("Dog eats dog food.")

class Fish(Animal):
  def __init__(self,h,w,wid):
    super().__init__(h,w,wid)
    self._hasFins=True
    self._finCount=6
    self._canSwim=True
    self._swimInOcean=True

  def eat(self):
    print("Fish eats fish food.")

class Spider(Animal):
  def __init__(self,h,w,wid,e):
    super().__init__(h,w,wid)
    self._laysEggs=True
    self._legs=8
    self._eyes = e
    self._spinsWebs=True
    self._scary=True

  def eat(self):
    print("Spider eats you.")

fito = Dog(1,1,1)
otif = Fish(1,1,1)
tifo = Spider(1,1,1,8)

fito.eat()
otif.eat()
tifo.eat()

fito.weight = 2
fito.height = 1.5
fito.width = 3

otif.weight = 2
otif.height = 1.5
otif.width = 3

tifo.weight = 2
tifo.height = 1.5
tifo.width = 3

print(fito.weight, fito.height, fito.width, otif.weight, tifo.weight)

class ArchitecturalStructure():
  pass

class Building(ArchitecturalStructure):
  pass

class ApartmentBuilding(Building)
  pass

class Dwelling(ArchitecturalStructure):
  pass

class Apartment(Dwelling):
  pass

class House(Dwelling):
  pass

class Tent():
  pass

class room():
  size = 'idk'

class Kitchen(room):
  pass

class LivingRoom(room):
  pass

class DiningRoom(room):
  pass

class Garage(room):
  pass

class RealEstateAgent():
  pass

class Remax():
  pass

class Agency():
  pass

class ResidentialZoning():
  pass