# -*- coding: utf-8 -*-
"""W15A01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKezsMpM2C3n0ATlo7jmYR-Ki_3_SZXv
"""

class Animal():
  def __init__(self):
    self.weight = 0
  def __str__(self, str):
    return ("Animal weight is %s" % (self.weight))

class Paycheck():
  def __init__(self,amt=0):
    self.amount=amt
  def __str__(self):
    return(f"Paycheck has $%.2f"%(self.amount))
  def __add__(self,obj):
    return Paycheck(self.amount + obj.amount)
  def __sub__(self,obj):
    return Paycheck(self.amount - obj.amount)
  def __mul__(self,obj):
    return Paycheck(self.amount * obj.amount)
  def __truediv__(self,obj):
    return Paycheck(self.amount / obj.amount)

pay = Paycheck(200)
pay2 = Paycheck(100)
pay3 = Paycheck(50)
print(pay - pay2 + pay3 * pay3 / pay3)
print(isinstance(pay3,Paycheck))