# -*- coding: utf-8 -*-
"""W15A02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x7TZISYpENr2VAe0cZgZUas-FF4OXMXS
"""

class Zoo():
  def __init__(self):
    self.animals = []

  def addAnimal(self,a):
    self.animals.append(a)

  def __len__(self):
    return len(self.animals)

  def __getitem__(self, idx):
    return self.animals[idx]

  def __setitem__(self,idx, obj):
    self.animals[idx] = obj

  def __delitem__(self, idx):
    del self.animals[idx]

  def __str__(self):
    return str(self.animals)

  def __iter__(self):
    self.currentIndex = 0
    return self

  def __next__(self):
    if self.currentIndex >= len(self):
      raise StopIteration
    idx = self.currentIndex
    self.currentIndex += 1
    return self.animals[idx]

  def __contains__(self, animal):
    for i in self:
      if animal == i:
        return True
    return False

class Animal():
  pass

class Lion(Animal):
  pass

class Tiger(Animal):
  pass

class Bear(Animal):
  pass

alpha = Zoo()
beta = Lion()
charlie = Tiger()
delta = Bear()

alpha.addAnimal(beta)
alpha.addAnimal(charlie)
alpha.addAnimal(delta)

print(len(alpha))

alpha[0] = Tiger()
print(alpha[0])
del alpha[2]

for i in alpha:
  print(i)

print(Bear() in alpha)